spring:
  application:
    name: "T1 Open School"

  jpa:
    hibernate:
      ddl-auto: none

  kafka:
    bootstrap-servers:
      - kafka:9092
    consumer:
      group-id: task-id
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.kmuradoff.openschooljava.adapter.in.kafka.MessageDeserializer
      enable-auto-commit: false
      properties:
        spring.json.trusted.packages: "*"
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    listener:
      ack-mode: manual
      type: batch
      poll-timeout: 3000

  mail:
    host: smtp.gmail.com
    port: 587
    username: muradoffk@gmail.com
    password: qtmkymjwqqbdczmz
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true